title: Shine YE
description: My Personal Blog
author: Shine
logo: /static/img/avatar.png
github: https://github.com/shuine
about: Android developer

baseurl: "https://shuine.github.io/blog.github.io"
url: "https://shuine.github.io/blog.github.io"

disqus_shortname: shine
google_analytics: UA-72862926-1

share:
  twitter_username: shine
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
